'use client';
import Image from 'next/image';
import { useState } from 'react';
import { LuArrowRight, LuImage, LuPackageCheck, LuCalendarDays, LuBadgeCheck } from 'react-icons/lu';
import base from '../whatsapp-api/WhatsAppLanding.module.css';
import styles from './RcsLanding.module.css';
const examples = [
  { label: 'Show an offer', icon: LuImage, title: 'Show the offer. Give customers a next step.', description: 'Bring a product or campaign to life with a rich card and a clear action. Help customers explore what interests them without typing a new question.', card: 'Meet your next weekend bag', message: 'A canvas weekender for your next short trip. Explore the collection and find your favourite.', action: 'Explore collection', result: 'This action would open your collection page.', tag: 'PRODUCT DISCOVERY', carouselCards: [['Meet your next weekend bag', 'A canvas weekender for short trips.', 'Explore collection'], ['Pack smarter for the weekend', 'Organisers and accessories for the journey.', 'View accessories'], ['Find a gift they will use', 'A considered travel gift, ready to explore.', 'See gift ideas']] },
  { label: 'Share an update', icon: LuPackageCheck, title: 'Put the update and the action together.', description: 'Send an order update with an action to view delivery details. Make the information customers need easier to find.', card: 'Your order is on its way', message: 'Order #4821 has been dispatched. Check the latest delivery details below.', action: 'Track my order', result: 'This action would open the customer’s tracking page.', tag: 'ORDER UPDATES', carouselCards: [['Your order is on its way', 'Order #4821 has been dispatched.', 'Track my order'], ['Your invoice is ready', 'Review the payment details for your order.', 'View invoice'], ['Need help with your order?', 'Connect with your support team.', 'Get help']] },
  { label: 'Confirm a booking', icon: LuCalendarDays, title: 'Make it easier to respond to a reminder.', description: 'Show the appointment details and let customers reply with a tap. Connect that response to the next step in your booking workflow.', card: 'Your appointment reminder', message: 'Your appointment is scheduled for tomorrow at 11:00 AM. Does this time still work for you?', action: 'Confirm appointment', result: 'The customer’s confirmation would be passed to your booking workflow.', tag: 'APPOINTMENT REMINDERS', carouselCards: [['Confirm your appointment', 'Tomorrow at 11:00 AM with our team.', 'Confirm time'], ['Choose another time', 'Pick a time that works better for you.', 'Change time'], ['Talk to our team', 'Ask a question before your appointment.', 'Contact us']] },
];
export default function RcsPreview() {
  const [active, setActive] = useState(0);
  const [tried, setTried] = useState(false);
  const [format, setFormat] = useState('carousel');
  const item = examples[active];
  function select(index) { setActive(index); setTried(false); setFormat('carousel'); }
  function onKeyDown(event) {
    if (!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return;
    event.preventDefault();
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? examples.length - 1 : (active + (event.key === 'ArrowRight' ? 1 : -1) + examples.length) % examples.length;
    select(next); document.getElementById(`rcs-tab-${next}`)?.focus();
  }
  return <div><div className={base.tabs} role="tablist" aria-label="RCS message examples" onKeyDown={onKeyDown}>{examples.map((example,index)=><button key={example.label} type="button" role="tab" id={`rcs-tab-${index}`} aria-selected={active===index} aria-controls="rcs-preview" tabIndex={active===index?0:-1} onClick={()=>select(index)}><example.icon aria-hidden="true" />{example.label}</button>)}</div>
    <div className={styles.preview} id="rcs-preview" role="tabpanel" aria-labelledby={`rcs-tab-${active}`}><div><span className={base.eyebrow}>{item.tag}</span><h3>{item.title}</h3><p>{item.description}</p><ol className={styles.flow}><li>Customer receives your branded message</li><li>They choose an action or reply</li><li>Your website or team continues the journey</li></ol><a className={base.textLink} href="#lead-form">See this for my business <LuArrowRight aria-hidden="true" /></a></div>
      <div className={styles.phone}><div className={styles.sender}><span>YB</span><div><strong>Your business <LuBadgeCheck aria-hidden="true" /></strong><small>Illustrative RCS conversation</small></div></div><div className={styles.formatSwitch} role="group" aria-label="Choose RCS card format"><span>HOW SHOULD CUSTOMERS EXPLORE?</span><button type="button" className={format === 'single' ? styles.selectedFormat : ''} onClick={() => { setFormat('single'); setTried(false); }}>One message</button><button type="button" className={format === 'carousel' ? styles.selectedFormat : ''} onClick={() => { setFormat('carousel'); setTried(false); }}>Compare options <em>Carousel</em></button></div>{format === 'carousel' ? <div className={styles.carouselWrap}><div className={styles.carouselIntro}><strong>Compare related choices in one message.</strong><span>Customers swipe across cards and choose the one they want.</span></div><div className={styles.carousel} aria-label="RCS rich card carousel preview">{item.carouselCards.map(([title, description, action], index) => <article className={styles.carouselCard} key={title}><div className={styles.carouselArt}>{active === 0 && index === 0 ? <Image src="/rcs-weekender-example.webp" alt="Illustrative canvas weekender bag product photo" width={720} height={480} sizes="180px" loading="lazy" /> : <item.icon aria-hidden="true" />}</div><div className={styles.cardPosition}>OPTION {index + 1} OF {item.carouselCards.length}</div><h4>{title}</h4><p>{description}</p><button type="button" onClick={() => setTried(true)}>{action}<LuArrowRight aria-hidden="true" /></button></article>)}</div><p className={styles.carouselHint}>Swipe or scroll sideways to compare options.</p></div> : <div className={styles.card}><div className={styles.art}>{active === 0 ? <Image src="/rcs-weekender-example.webp" alt="Illustrative canvas weekender bag product photo" width={720} height={480} sizes="(max-width: 540px) 280px, 310px" loading="lazy" /> : <><item.icon aria-hidden="true" /><span>{item.tag}</span></>}</div><h4>{item.card}</h4><p>{item.message}</p><button type="button" onClick={()=>setTried(true)}>{item.action}<LuArrowRight aria-hidden="true" /></button></div>}<p className={styles.result} aria-live="polite">{tried ? (format === 'carousel' ? 'The selected option can open a product page, continue a conversation or trigger your workflow.' : item.result) : 'Try an action to see the next step.'}</p><p className={styles.note}>Example only. RCS carousels use 2–10 vertical rich cards; device support and rendering can vary.</p></div>
    </div></div>;
}
